// src/game/EnemyData.js

export const ENEMY_TYPES = {
  GROANER: 'groaner',
  CRAWLER: 'crawler',
  MOLD: 'mold',
  CLAWER: 'clawer',
  SLIME: 'slime',
  RUNNER: 'runner',
  FATSO: 'fatso',
  HOWLER: 'howler',
  STICKER: 'sticker',
  MUSHROOM: 'mushroom',
  NONHUMAN: 'nonhuman',
  RAT_KING: 'ratKing'
}

export const ENEMIES = {
  [ENEMY_TYPES.GROANER]: {
    name: 'Стонущий',
    char: 'g',
    color: '#88aaaa',
    hp: 20,
    armor: 0,
    damageMin: 3,
    damageMax: 6,
    damageType: 'blunt',
    range: 1,
    initiative: 2,
    accuracy: 0.60,
    ap: { max: 10, moveCost: 1 },
    fovRadius: 8,
    features: ['deathScream'],
    description: 'При смерти издаёт крик, привлекающий подкрепление'
  },

  [ENEMY_TYPES.CRAWLER]: {
    name: 'Ползун',
    char: 'c',
    color: '#88aa88',
    hp: 15,
    armor: 2,
    damageMin: 2,
    damageMax: 4,
    damageType: 'bite',
    range: 1,
    initiative: 4,
    accuracy: 0.70,
    ap: { max: 10, moveCost: 1 },
    fovRadius: 8,
    features: ['infection'],
    infectionChance: 0.05,
    description: 'При попадании +5% заражения цели'
  },

  [ENEMY_TYPES.MOLD]: {
    name: 'Плесневик',
    char: 'm',
    color: '#88aa55',
    hp: 25,
    armor: 1,
    damageMin: 4,
    damageMax: 8,
    damageType: 'spore',
    range: 3,
    initiative: 3,
    accuracy: 0.65,
    ap: { max: 10, moveCost: 1 },
    fovRadius: 8,
    features: ['ranged', 'infection'],
    infectionChance: 0.05,
    ignoreLos: true,
    description: 'Дальняя атака спорами, не требует линии видимости'
  },

  [ENEMY_TYPES.CLAWER]: {
    name: 'Когтистый',
    char: 'C',
    color: '#cc8866',
    hp: 30,
    armor: 2,
    damageMin: 6,
    damageMax: 12,
    damageType: 'slash',
    range: 1,
    initiative: 6,
    accuracy: 0.75,
    ap: { max: 10, moveCost: 1 },
    fovRadius: 8,
    features: ['doubleAttack'],
    doubleAttackPenalty: 0.20,
    description: 'Атакует дважды за ход (но с -20% точности второй удар)'
  },

  [ENEMY_TYPES.SLIME]: {
    name: 'Слизень',
    char: 's',
    color: '#66cc66',
    hp: 40,
    armor: 5,
    damageMin: 5,
    damageMax: 7,
    damageType: 'acid',
    range: 1,
    initiative: 1,
    accuracy: 0.80,
    ap: { max: 10, moveCost: 2 },
    fovRadius: 8,
    features: ['corrodeArmor'],
    armorReduction: 1,
    description: 'При попадании разъедает броню (-1 защита цели, суммируется)'
  },

  [ENEMY_TYPES.RUNNER]: {
    name: 'Бегунок',
    char: 'r',
    color: '#aa8866',
    hp: 18,
    armor: 0,
    damageMin: 4,
    damageMax: 6,
    damageType: 'bite',
    range: 1,
    initiative: 8,
    accuracy: 0.60,
    ap: { max: 12, moveCost: 1 }, // Больше AP для скорости
    fovRadius: 10,
    features: ['fast'],
    description: 'Очень быстрый, всегда ходит первым'
  },

  [ENEMY_TYPES.FATSO]: {
    name: 'Толстяк',
    char: 'F',
    color: '#aa8844',
    hp: 60,
    armor: 3,
    damageMin: 8,
    damageMax: 14,
    damageType: 'blunt',
    range: 1,
    initiative: 2,
    accuracy: 0.70,
    ap: { max: 8, moveCost: 2 },
    fovRadius: 8,
    features: ['explodeOnDeath'],
    explosionDamageMin: 10,
    explosionDamageMax: 15,
    explosionRadius: 2,
    explosionInfection: 0.20,
    description: 'При смерти взрывается, нанося урон по области'
  },

  [ENEMY_TYPES.HOWLER]: {
    name: 'Воющий',
    char: 'h',
    color: '#aa88aa',
    hp: 22,
    armor: 1,
    damageMin: 0,
    damageMax: 0,
    damageType: 'none',
    range: 999,
    initiative: 5,
    accuracy: 1.00,
    ap: { max: 10, moveCost: 1 },
    fovRadius: 8,
    features: ['buffAllies'],
    initiativeBonus: 2,
    description: 'Не атакует, но воем даёт +2 инициативы всем тварям на карте'
  },

  [ENEMY_TYPES.STICKER]: {
    name: 'Прилипала',
    char: 'S',
    color: '#88ccaa',
    hp: 12,
    armor: 4,
    damageMin: 2,
    damageMax: 4,
    damageType: 'immobilize',
    range: 1,
    initiative: 4,
    accuracy: 0.90,
    ap: { max: 10, moveCost: 1 },
    fovRadius: 8,
    features: ['immobilize'],
    immobilizeDuration: 1,
    description: 'При попадании обездвиживает цель на 1 ход'
  },

  [ENEMY_TYPES.MUSHROOM]: {
    name: 'Грибник',
    char: 'M',
    color: '#aa77aa',
    hp: 35,
    armor: 2,
    damageMin: 6,
    damageMax: 10,
    damageType: 'spore',
    range: 2,
    initiative: 3,
    accuracy: 0.70,
    ap: { max: 10, moveCost: 1 },
    fovRadius: 8,
    features: ['leaveSpores'],
    sporeRadius: 3,
    sporeInfection: 0.10,
    description: 'При смерти оставляет зону спор'
  },

  [ENEMY_TYPES.NONHUMAN]: {
    name: 'Нелюдь',
    char: 'N',
    color: '#ccaa88',
    hp: 45,
    armor: 3,
    damageMin: 8,
    damageMax: 14,
    damageType: 'weapon',
    range: 1,
    initiative: 5,
    accuracy: 0.65,
    ap: { max: 10, moveCost: 1 },
    fovRadius: 10,
    features: ['dropsWeapon', 'canFollowOrders'],
    description: 'Использует оружие, понимает приказы'
  },

  [ENEMY_TYPES.RAT_KING]: {
    name: 'Крысиный король',
    char: 'R',
    color: '#cc8866',
    hp: 30,
    armor: 1,
    damageMin: 2,
    damageMax: 6,
    damageType: 'bite',
    range: 1,
    initiative: 7,
    accuracy: 0.80,
    ap: { max: 10, moveCost: 1 },
    fovRadius: 8,
    features: ['summonRats'],
    summonCountMin: 1,
    summonCountMax: 3,
    description: 'Каждый ход призывает крыс'
  }
}
