// src/engine/components/index.js

export { default as Component } from './Component.js'
export { default as PositionComponent } from './PositionComponent.js'
export { default as RenderComponent } from './RenderComponent.js'
export { default as HealthComponent } from './HealthComponent.js'
export { default as HungerComponent } from './HungerComponent.js'
export { default as EnergyComponent } from './EnergyComponent.js'
export { default as CombatComponent } from './CombatComponent.js'
export { default as PlayerComponent } from './PlayerComponent.js'
export { default as AIComponent } from './AIComponent.js'
export { default as MovementComponent } from './MovementComponent.js'
export { default as InventoryComponent } from './InventoryComponent.js'
export { default as EnvironmentComponent } from './EnvironmentComponent.js'
export { default as DoorComponent } from './DoorComponent.js'
export { default as ItemComponent } from './ItemComponent.js'
export { default as WeightComponent } from './WeightComponent.js'
